---
x-common-config: &common-config
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  deploy:
    resources:
      limits:
        cpus: '1.0'
        memory: 1G
      reservations:
        memory: 512M

services:
  wiki-web:
    image: ${BLUESPICE_WIKI_IMAGE}
    container_name: ${CONTAINER_PREFIX}-wiki-web
    restart: unless-stopped
    entrypoint: ["/scripts/start-web-wrapper.sh"]
    networks:
      - bluespice-network
    tmpfs:
      - /tmp/wiki:uid=1002,gid=1002
    volumes:
      - /opt/bluespice/scripts:/scripts:ro
      - ${DATA_DIR}/${WIKI_NAME}:/data/bluespice
      - ${DATA_DIR}/${WIKI_NAME}/simplesamlphp:/data/simplesamlphp
      - ${DATA_DIR}/${WIKI_NAME}/extensions/PluggableAuth:/app/bluespice/w/extensions/PluggableAuth
      - ${DATA_DIR}/${WIKI_NAME}/extensions/OpenIDConnect:/app/bluespice/w/extensions/OpenIDConnect
      - ${DATA_DIR}/${WIKI_NAME}/extensions/GTag:/app/bluespice/w/extensions/GTag
      - ${DATA_DIR}/${WIKI_NAME}/extensions/SemanticMediaWiki:/app/bluespice/w/extensions/SemanticMediaWiki
      - ${DATA_DIR}/${WIKI_NAME}/extensions/SemanticExtraSpecialProperties:/app/bluespice/w/extensions/SemanticExtraSpecialProperties
    environment:
      - WIKI_NAME=${WIKI_NAME}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_TYPE=${DB_TYPE}
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_PORT=${CACHE_PORT}
      - EDITION=${EDITION}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - WIKI_HOST=${WIKI_HOST}
      - WIKI_PROTOCOL=https
      - WIKI_PORT=443
      - WIKI_SERVER=https://${WIKI_HOST}
      - DATADIR=/data/bluespice
      - WIKI_PRE_INIT_SETTINGS_FILE=/data/bluespice/pre-init-settings.php
      - WIKI_POST_INIT_SETTINGS_FILE=/data/bluespice/post-init-settings.php
      - WIKI_BASE_PATH=/
      - INTERNAL_WIKI_SECRETKEY=${INTERNAL_WIKI_SECRETKEY}
      - INTERNAL_WIKI_UPGRADEKEY=${INTERNAL_WIKI_UPGRADEKEY}
      - INTERNAL_WIKI_TOKEN_AUTH_SALT=${INTERNAL_WIKI_TOKEN_AUTH_SALT}
      - INTERNAL_WIRE_API_KEY=${INTERNAL_WIRE_API_KEY}
    <<: *common-config
    labels:
      com.bluespice.service: "wiki-web"
      com.bluespice.type: "application"
      com.bluespice.wiki: ${WIKI_NAME}

  wiki-task:
    image: ${BLUESPICE_WIKI_IMAGE}
    container_name: ${CONTAINER_PREFIX}-wiki-task
    restart: unless-stopped
    entrypoint: ["/scripts/start-task-wrapper.sh"]
    command: ["--runAll"]
    environment:
      - WIKI_NAME=${WIKI_NAME}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_TYPE=${DB_TYPE}
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_PORT=${CACHE_PORT}
      - EDITION=${EDITION}
      - WIKI_HOST=${WIKI_HOST}
      - WIKI_PROTOCOL=https
      - WIKI_PORT=443
      - WIKI_SERVER=https://${WIKI_HOST}
      - DATADIR=/data/bluespice
      - WIKI_PRE_INIT_SETTINGS_FILE=/data/bluespice/pre-init-settings.php
      - WIKI_POST_INIT_SETTINGS_FILE=/data/bluespice/post-init-settings.php
      - WIKI_BASE_PATH=/
      - INTERNAL_WIKI_SECRETKEY=${INTERNAL_WIKI_SECRETKEY}
      - INTERNAL_WIKI_UPGRADEKEY=${INTERNAL_WIKI_UPGRADEKEY}
      - INTERNAL_WIKI_TOKEN_AUTH_SALT=${INTERNAL_WIKI_TOKEN_AUTH_SALT}
      - INTERNAL_WIRE_API_KEY=${INTERNAL_WIRE_API_KEY}
    networks:
      - bluespice-network
    tmpfs:
      - /data:uid=1002,gid=1002
      - /tmp/wiki:uid=1002,gid=1002
    volumes:
      - /opt/bluespice/scripts:/scripts:ro
      - ${DATA_DIR}/${WIKI_NAME}:/data/bluespice
      - ${DATA_DIR}/${WIKI_NAME}/simplesamlphp:/data/simplesamlphp
      - ${DATA_DIR}/${WIKI_NAME}/extensions/PluggableAuth:/app/bluespice/w/extensions/PluggableAuth
      - ${DATA_DIR}/${WIKI_NAME}/extensions/OpenIDConnect:/app/bluespice/w/extensions/OpenIDConnect
      - ${DATA_DIR}/${WIKI_NAME}/extensions/GTag:/app/bluespice/w/extensions/GTag
      - ${DATA_DIR}/${WIKI_NAME}/extensions/SemanticMediaWiki:/app/bluespice/w/extensions/SemanticMediaWiki
      - ${DATA_DIR}/${WIKI_NAME}/extensions/SemanticExtraSpecialProperties:/app/bluespice/w/extensions/SemanticExtraSpecialProperties
    <<: *common-config
    labels:
      com.bluespice.service: "wiki-task"
      com.bluespice.type: "application"
      com.bluespice.wiki: ${WIKI_NAME}

  wire:
    image: ${BLUESPICE_SERVICE_REPOSITORY}/wire:${VERSION}
    container_name: ${CONTAINER_PREFIX}-wire
    restart: unless-stopped
    networks:
      - bluespice-network
    environment:
      - WIRE_LOG_LEVEL=info
      - WIRE_WIKI_BASE_PATH=http://${CONTAINER_PREFIX}-wiki-web:9090
      - WIRE_API_KEY=${INTERNAL_WIRE_API_KEY}
      - WIRE_TOKEN_SALT=${INTERNAL_WIKI_TOKEN_AUTH_SALT}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PATH=/_wire
      - VIRTUAL_PORT=3333
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    <<: *common-config
    labels:
      com.bluespice.service: "wire"
      com.bluespice.type: "application"
      com.bluespice.wiki: ${WIKI_NAME}

networks:
  bluespice-network:
    external: true
