---
x-common-config: &common-config
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: 256M
      reservations:
        memory: 128M

services:
  prepare:
    image: ${BLUESPICE_SERVICE_REPOSITORY}/helper:${VERSION}
    container_name: ${CONTAINER_PREFIX}-prepare
    command: prepare-bluespice
    networks:
      - bluespice-network
    volumes:
      - ${DATA_DIR}:/data
    environment:
      - DB_NAME=${WIKI_NAME}
    <<: *common-config
    labels:
      com.bluespice.service: "helper"
      com.bluespice.type: "maintenance"
      com.bluespice.group: "prepare"
      com.bluespice.wiki: ${WIKI_NAME}

  upgrade:
    image: ${BLUESPICE_SERVICE_REPOSITORY}/helper:${VERSION}
    container_name: ${CONTAINER_PREFIX}-upgrade
    command: ${UPGRADE_ACTION:-sleep 1}
    networks:
      - bluespice-network
    volumes:
      - ${DATA_DIR}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VERSION=${VERSION}
      - EDITION=${EDITION}
      - DATA_DIR=${DATA_DIR}
      - WIKI_NAME=${WIKI_NAME}
      - WIKI_LANG=${WIKI_LANG:-en}
      - WIKI_HOST=${WIKI_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    <<: *common-config
    labels:
      com.bluespice.service: "upgrade"
      com.bluespice.type: "maintenance"
      com.bluespice.group: "upgrade"
      com.bluespice.wiki: ${WIKI_NAME}

networks:
  bluespice-network:
    external: true
