---
x-common-config: &common-config
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: 512M
      reservations:
        memory: 256M

services:
  collabpads:
    image: ${BLUESPICE_SERVICE_REPOSITORY}/collabpads:${VERSION}
    container_name: ${CONTAINER_PREFIX}-collabpads
    restart: unless-stopped
    depends_on:
      collabpads-database:
        condition: service_healthy
        restart: true
    networks:
      - bluespice-network
    environment:
      - COLLABPADS_BACKEND_WIKI_BASEURL=http://${CONTAINER_PREFIX}-wiki-web:9090
      - COLLABPADS_BACKEND_MONGO_DB_HOST=${CONTAINER_PREFIX}-collabpads-database
      - COLLABPADS_BACKEND_MONGO_DB_PORT=27017
      - COLLABPADS_BACKEND_LOG_LEVEL=info
      - COLLABPADS_BACKEND_PORT=8081
      - VIRTUAL_HOST=${WIKI_HOST}
      - VIRTUAL_PATH=/_collabpads/
      - VIRTUAL_PORT=8081
    <<: *common-config
    labels:
      com.bluespice.service: "collabpads"
      com.bluespice.type: "application"
      com.bluespice.wiki: ${WIKI_NAME}

  collabpads-database:
    image: mongo:8.0
    container_name: ${CONTAINER_PREFIX}-collabpads-database
    restart: unless-stopped
    networks:
      - bluespice-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      start_period: 5s
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${DATADIR}/${WIKI_NAME}/database-collabpads:/data/db
    <<: *common-config
    labels:
      com.bluespice.service: "collabpads-database"
      com.bluespice.type: "database"
      com.bluespice.wiki: ${WIKI_NAME}

networks:
  bluespice-network:
    external: true
